### ISSUE TITLE
Add support for VS 2017

### ISSUE THREAD

**Issue by MichaelGrafnetter** [deadlydog/Invoke-MsBuild#14]
The Get-VisualStudioCommandPromptPath does not locate VS 2017. I admit that this is a tricky one as you can now have multiple VS 2017 instances. I would suggest using the vswhere.exe command with -legacy parameter, which can also locate downlevel VS directories.

**Comment by deadlydog** [comment]
Completed as part of PR #16, version 2.3.0. I have only verified that it works on my local machine, so if you want to give it a try I would appreciate knowing if it also worked for you or not. Thanks.

**Comment by MichaelGrafnetter** [comment]
Thanks, I will test it with VS 2013 and 2017.

**Comment by deadlydog** [comment]
Turns out I didn't implement it quite right. 2017 support is truly there in PR #17, release v2.3.1. Thanks.

**Comment by MichaelGrafnetter** [comment]
Thx, I just want to confirm that it forks on my VS 2013 and 2017 build machines.
