### ISSUE TITLE
Question about releases

### ISSUE THREAD

**Issue by majkinetor** [deadlydog/Invoke-MsBuild#15]
Github releases is currently at v2.1.0 and Posh galery at v2.2.0.

Is it possible to maintain consistency here?

I want to maintain chocolatey package up to date and would like to base it on Github releases:
https://chocolatey.org/packages/invokemsbuild

I could keep this up to date always with my bot as long as you release on both places. 

If you can't keep both places up to date, please let me know here.

**Comment by deadlydog** [comment]
Sorry, I'll try to keep them consistent. I already have an automated way or creating and publishing new packages to the PowerShell Gallery. It would be awesome if I could also automate publishing new releases to GitHub, and then just use the same script to publish to both places.

**Comment by majkinetor** [comment]
https://github.com/majkinetor/au/blob/master/scripts/Github-CreateRelease.ps1
