### ISSUE TITLE
Invoke-MsBuild used with powershell and octopus

### ISSUE THREAD

**Issue by v703612** [deadlydog/Invoke-MsBuild#20]
Hello,

We are currently trying your Invoke-MsBuild in combination with powershell and octopusdeploy. This is currently working great but we don't get the rolling output of the msbuild in our octopus overview. This is even not happening when we are trying to build in powershell. Are we missing a parameter?

==>    $buildResult = Invoke-MsBuild  -Path $deployloc  -BuildLogDirectoryPath c:\temp\ -MsBuildParameters "/target:deploy /property:Database=test;server=test /v:d"

**Comment by deadlydog** [comment]
Try using the `-ShowBuildOutputInCurrentWindow` switch, like this:
```
Invoke-MsBuild -Path $pathToGoodSolution -ShowBuildOutputInCurrentWindow
```

I notice that I don't have it in the examples on the ReadMe.md page, so you'd only discover it if you looked at the PowerShell documentation (e.g. Get-Help), or viewed the script source code. I'll get the ReadMe updated.

Let me know if that works for you.

**Comment by v703612** [comment]
Thank you very much! this works.
