### ISSUE TITLE
Add support for .NET Framework 4.5.2

### ISSUE THREAD

**Issue by MichaelGrafnetter** [deadlydog/Invoke-MsBuild#21]
Hi, when invoking Invoke-MSBuild with PS 5 and .NET Framework 4.5.2, I get an exception saying that "'CurrentCulture' is a ReadOnly property".

See [MSDN](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.currentculture(v=vs.110).aspx):

> In the .NET Framework 4.5.2 and earlier versions, the CurrentCulture property is read-only; that is, you can retrieve the property value, but you cannot set it. To change the current culture, you assign the CultureInfo object that represents the new culture to the Thread.CurrentThread.CurrentCulture property. Starting with the .NET Framework 4.6, the CurrentCulture property is read-write; you can both set and retrieve the property's value. If you do set the property value to a CultureInfo object that represents a new culture, the value of the Thread.CurrentThread.CurrentCulture property also changes.

**Comment by deadlydog** [comment]
Thanks for reporting the bug and MSDN link/snippet @MichaelGrafnetter. Can you try version 2.4.1 of the script/nuget package and let me know if it fixed the issue for you please. I'm going to close this issue, but please reopen it if the bug is still present. Thanks!

**Comment by MichaelGrafnetter** [comment]
Yes @deadlydog, that fixed it, thanks.
