### ISSUE TITLE
The module only works on 64-bit platforms

### ISSUE THREAD

**Issue by MichaelGrafnetter** [deadlydog/Invoke-MsBuild#24]
Hi, I found another bug in this otherwise great module. ;-) When running Invoke-MSBuild on a 32-bit Windows, I get this exception:

` Get-Item : Cannot find path 'Env:\ProgramFiles(x86)' because it does not exist.
At C:\...\Invoke-MsBuild.psm1:674 char:36
`
Yes, I know that 32-bit build machines are not very common these days...

**Comment by deadlydog** [comment]
Ok, I believe this should be fixed in v2.4.2 @MichaelGrafnetter. Want to give it a try and let me know please. I'm going to close this issue for now, but reopen it if the bug still exists. Thanks!

**Comment by MichaelGrafnetter** [comment]
Thanks, @deadlydog. Unfortunately, the bug still exists as o v 2.5.0. The same exception gets thrown, now on line 682.

**Comment by deadlydog** [comment]
Ok, hopefully it's actually fixed this time in v2.5.1. Give it a shot and let me know. Thanks!

**Comment by MichaelGrafnetter** [comment]
That's it, @deadlydog. Thank you very much. Tested it on both 32-bit and 64-bit systems.
