### ISSUE TITLE
Finishes with BuildSucceeded=False, even though msbuild only encounters warnings

### ISSUE THREAD

**Issue by ic3guy** [deadlydog/Invoke-MsBuild#27]
With MSbuild version: 4.6.1590.0
Running Visual Studio 2017
The solution I am building is predominantly VB.NET code.  

MsBuild only reports 86 Warnings(s) and 0 Errors(s), however Invoke-MsBuild finishes with a BuildSucceeded=False. I've isolated this to the return code of MsBuild not being equal to 0. Because if I remove that check condition ( $result.MsBuildProcess.ExitCode -eq 0)  from line 441 in the script, then BuildSucceeded=True. That means that the string "Build FAILED" is not in the build output.

I've tried digging into the MsBuild docs to see if BC warnings (from vbc) are handled differently than that C# warnings. I've got a suspicion they are, but cannot confirm.

**Comment by deadlydog** [comment]
Hi @ic3guy, I just added a new test that builds a solution that generates warnings, but no errors, and Invoke-MsBuild does seem to report that it built successfully.

Can you perhaps modify the script to report the ExitCode that was output by MSBuild.exe and let me know what it is? Looking up the exit code may give us additional info. Thanks.

**Comment by ic3guy** [comment]
Ah I should have thought to do that.

The $result.MsBuildProcess.ExitCode I get is 121.

**Comment by deadlydog** [comment]
Thanks ic3guy, unfortunately I couldn't find anything on msbuild error code 121, and still haven't been able to reproduce it. I'm going to close this issue, but if it's still occurring for you let me know and we can reopen it. Thanks.
