### ISSUE TITLE
Use AppVeyor for CI

### ISSUE THREAD

**Issue by nschonni** [deadlydog/Invoke-MsBuild#28]
This would give you test coverage for PRs.

You've got some good PS scripts for the Gallery and GitHub publishing already, but you could automate pushing the [NuGet](https://www.appveyor.com/docs/deployment/nuget/) and GitHub(https://www.appveyor.com/docs/deployment/github/) releases whenever you push a tag

**Comment by deadlydog** [comment]
If it was free I might consider it, but it doesn't provide enough benefits over my existing scripts to justify paying a minimum $30/month. I honestly don't mind being explicit about pushing my releases, as I can then make sure an appropriate semantic version and release notes are assigned to the release.

I do agree though that I should start running my tests automatically on commit, or before publishing a new release. Once I switch to using Pester for testing I'll look at getting that hooked up.

Thanks for your interest, but I'm going to continue rolling with my existing scripts.

**Comment by nschonni** [comment]
It is free for open source projects https://www.appveyor.com/pricing/ $30/month is only for private/closed source projects

**Comment by deadlydog** [comment]
Oh, I missed that. Thanks :) I'll keep it in mind.

**Comment by nschonni** [comment]
Not sure if you want to reopen this to track it. Tried playing just with the web settings https://ci.appveyor.com/project/nschonni/invoke-msbuild/build/1.0.3
