### ISSUE TITLE
Can't create/find build log normally, hangs bypassing devtools

### ISSUE THREAD

**Issue by thnk2wn** [deadlydog/Invoke-MsBuild#32]
When I use this it can never seem to create the build log. If I add the parameter to bypass dev tools it seems to build and generate a log but no output is shown and it seems to hang even though the build finished. Windows 10, PowerShell 5, VS 2017 Enterprise.

> C:\source\cbsnorthstar
>
>[Feature/CheckSearchServerTime]> Invoke-MSBuild NorthStar.OrderEntry.POS.sln
>WARNING: Cannot find the build log file at
>'C:\Users\geoffh\AppData\Local\Temp\NorthStar.OrderEntry.POS.sln.msbuild.log', so unable to determine >if build
>succeeded or not.
>
>Name                           Value
>----                           -----
>Message                        Cannot find the build log file at 'C:\Users\geoffh\AppData\Local\Temp\NorthStar.Order...
>MsBuildProcess
>BuildLogFilePath               C:\Users\geoffh\AppData\Local\Temp\NorthStar.OrderEntry.POS.sln.msbuild.log
>BuildErrorsLogFilePath         >C:\Users\geoffh\AppData\Local\Temp\NorthStar.OrderEntry.POS.sln.msbulid.errors.log
>BuildSucceeded
>ItemToBuildFilePath            NorthStar.OrderEntry.POS.sln
>CommandUsedToBuild             cmd.exe /k " "C:\Program Files (x86)\Microsoft Visual >Studio\2017\Enterprise\Common7\...
>BuildDuration                  00:00:04.0651079

**Comment by thnk2wn** [comment]
I have to fully qualify the filename to avoid the log error - can't use relative to current working directory or pattern though parts of it seemed to work that way.

invoke-msbuild -path "c:\Full\Path\To\MySolution.sln"

That avoids the log error but then exhibits the same hanging msbuild behavior.

**Comment by deadlydog** [comment]
Thanks @thnk2wn for reporting an issue with using a relative file path for the build log; I'll see if I can reproduce it on my end.

You mentioned though that in addition to the log file not being created, the Invoke-MsBuild process seemed to hang and never complete? Is that happening all the time, or just under certain conditions or for certain projects/solutions?

**Comment by thnk2wn** [comment]
@deadlydog I just tried it on an empty console app and it worked so maybe it's specific to our solution. This solution is comprised of a UWP app, a UWP test project, a .net core 1.0 console app, a UWP class library, and a .net standard 1.4 portable class library.

I see the build logs showing me the build finished but the powershell cmdlet never "comes back" and in task manager I see a MSBuild process hanging around.

**Comment by jesseconnr** [comment]
The issue with hanging is likely due to the `/maxcpucount` switch, which is shown in the example on the readme. Without `/nr:false` the MSBuild processes never exit and the command never returns because it uses `-Wait`. See the stack answer below for a more detailed account. 

https://stackoverflow.com/questions/13510465/the-mystery-of-stuck-inactive-msbuild-exe-processes-locked-stylecop-dll-nuget

**Comment by deadlydog** [comment]
Closing this issue as there's been no response. Hopefully that means it's fixed :) We can reopen this if we find it's still occurring.
