### ISSUE TITLE
Convert to double returns wrong value, because of current culture.

### ISSUE THREAD

**Issue by jame-developer** [deadlydog/Invoke-MsBuild#33]
If the current culture is 'de-DE' for example, the conversion results in wrong values.
For example: Found version string "14.0" will be converted to 140 which could not be found.
Adding `[System.Threading.Thread]::CurrentThread.CurrentCulture = 'en-US'` before conversion calls or for the whole script solves the problem.

https://github.com/deadlydog/Invoke-MsBuild/blob/2460dc4569cafd94df0b722365ef645675a01c7d/src/Invoke-MsBuild/Invoke-MsBuild.psm1#L679

**Comment by deadlydog** [comment]
I believe this should now be fixed in v2.7.1 @jame-developer . If you still have issues let me know here. Thanks for the detailed report, and sorry it took so long to get this fixed.
