### ISSUE TITLE
How to publish a web project to a specific destination folder

### ISSUE THREAD

**Issue by vr-japs-asuncion** [deadlydog/Invoke-MsBuild#36]
Is there a way we could publish a web project to a supplied path in the params? If so, can it be deployed without adding Profile in the project?

**Comment by deadlydog** [comment]
If MsBuild.exe supports it, then Invoke-MsBuild will support it as well, as Invoke-MsBuild is mostly just a pass through to MsBuild.exe.

Doing a quick Google search, I didn't find a way of deploying from MsBuild.exe without using a publish profile (that doesn't mean it's not possible though, I just didn't find it). I did find [this StackOverflow answer](https://stackoverflow.com/a/14232754/602585) that shows how to do it with a publish profile though. The additional parameters being passed to MsBuild.exe should be able to be provided via Invoke-MsBuild's `-MsBuildParameters` parameter.

Hopefully that answers your question and gets you going 🙂

**Comment by vr-japs-asuncion** [comment]
This helps @deadlydog , thanks a lot :)
