### ISSUE TITLE
Test run failed

### ISSUE THREAD

**Issue by sergey-bastrakov** [deadlydog/Invoke-MsBuild#4]
I am getting error when run test.

> Invoke-MsBuild : Unexpected error occurred while building "F:\Temp\Invoke-MsBuild\Tests\SolutionThatShouldBuildSuccessfully\SolutionThatShouldBuildSuccessfully.sln": Exception calling "ToDouble" with "1" argument(s): "Input string was not in a correct format."
> At F:\Temp\Invoke-MsBuild\Tests\RunTests.ps1:22 char:6
> - if ((Invoke-MsBuild -Path $pathToGoodSolution).BuildSucceeded -eq $true) { Write ...
> -      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>   - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-MsBuild
> 
> Test 1 failed.
> At F:\Temp\Invoke-MsBuild\Tests\RunTests.ps1:22 char:105
> - ... ssed" } else { throw "Test $testNumber failed." }
> -                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : OperationStopped: (Test 1 failed.:String) [], RuntimeException
>   - FullyQualifiedErrorId : Test 1 failed.

**Comment by deadlydog** [comment]
Sorry it took so long for me to see this. Apparently I didn't have my notifications configured properly in GitHub :(

I believe this issue has been fixed in the latest release of Invoke-MsBuild (v2.2.0). Can you try it again and let me know if you still have issues please. Thanks.

**Comment by deadlydog** [comment]
Going to assume this issue is fixed. Closing.
