### ISSUE TITLE
please support 'bin log' for structured log viewer 'http://msbuildlog.com/'

### ISSUE THREAD

**Issue by mediabuff** [deadlydog/Invoke-MsBuild#43]

**Comment by deadlydog** [comment]
It looks like you just need to provide the `/binaryLogger` (or `/bl`) MSBuild parameter to have it creating a `.binlog` file for you. So it's already supported. You just need to do something like this to generate it.

```
Invoke-MsBuild -Path "C:\Some Folder\MyProject.csproj" -MsBuildParameters "/target:Clean;Build /bl:output.binlog"
```

If this isn't what you were asking for, please provide more info and I'll reopen this.
