### ISSUE TITLE
VS 2022 support

### ISSUE THREAD

**Issue by ajax16384** [deadlydog/Invoke-MsBuild#46]
VS changed it'ss default msbuild  location on x64 from  "C:\Program Files (x86)\Microsoft Visual Studio" to "C:\Program Files\Microsoft Visual Studio"  (but also left old path for installer)
so Get-CommonVisualStudioDirectoryPath should also probe real VS related binaries

**Comment by deadlydog** [comment]
@ajax16384 VS 2022 should now be supported in v2.7.0. Thanks for submitting the issue 👍 If you run into any problems let me know in this issue.
