### ISSUE TITLE
Registry on this system does not appear to contain the path to the Msbuild.exe directory

### ISSUE THREAD

**Issue by Jerome2606** [deadlydog/Invoke-MsBuild#7]
Hello,

I'm trying to use this plugin to build my solution but I got this error:

```
Get-Item : Cannot find path 'HKLM:\SOFTWARE\Microsoft\MSBuild\ToolsVersions\140,0' because it does not exist.
At C:\Users\jlm\Documents\projects\Invoke-MsBuild\Invoke-MsBuild\Invoke-MsBuild.psm1:489 char:34
+ ... onsKeyToUse = Get-Item -Path $registryPathToMsBuildToolsLatestVersion
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...sVersions\140,0:String) [Get-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

Invoke-MsBuild : Unexpected error occurred while building "C:\Users\jlm\Documents\projects\ccc.sln": The registry on this system does not appear to contain the path to the MsBuild.exe directory.
```

I understand that I miss a registry but where, how ?

I'm on Windows 10 x64 with VS 2015 installed

My regedit into HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0: 

http://hpics.li/f544a5b

Best regards,

**Comment by deadlydog** [comment]
Sorry it took so long for me to see this. Apparently I didn't have my notifications configured properly in GitHub :(

Thanks so much for reporting the bug AND creating the pull request to fix it! I've merged in the fix, so hopefully this is no longer an issue. Thanks again!
