### ISSUE TITLE
Config Transforms

### ISSUE THREAD

**Issue by richarddavenport** [deadlydog/Invoke-MsBuild#8]
Is there an easy way to do web.config/app.config transforms with Invoke-MsBuild? I have seen [this article](http://sedodream.com/2010/04/26/ConfigTransformationsOutsideOfWebAppBuilds.aspx) but not sure how to use that with this project. Any guidance would be awesome. Thanks!

**Comment by Jerome2606** [comment]
Hello,

I use https://visualstudiogallery.msdn.microsoft.com/579d3a78-3bdd-497c-bc21-aa6e6abbc859 this extension.
It will add into the project the same way that in your article.

I use the publish profile to select which configuration to use and launch it like:

```
$parameterMSBuild = "/property:Configuration=" + $BuildConfigurationKey
if (![string]::IsNullOrEmpty($PublishProfileKey)){
    $parameterMSBuild = "/p:DeployOnBuild=true /p:PublishProfile=" + $PublishProfileKey + " /p:Configuration=" + $ConfigTransformConfigurationKey
}

$msbuildCommand = "/target:Clean;Build " + $parameterMSBuild

$buildProcess = Invoke-MsBuild -Path $WebAppFullPath -Params $msbuildCommand -PassThru
```

**Comment by deadlydog** [comment]
Sorry it took so long for me to see this. Apparently I didn't have my notifications configured properly in GitHub :(

@richarddavenport In the example given on your link, the line he is using to call msbuild is:

```
msbuild trans.proj /t:Demo
```

To use Invoke-MsBuild, you should simply need to replace that line with:

```
Invoke-MsBuild -Path trans.proj -MsBuildParameters "/t:Demo"
```

That should be all that's needed to make that link's example work with Invoke-MsBuild.

**Comment by richarddavenport** [comment]
Thanks!
