### ISSUE TITLE
Would be really nice to change log verbosity

### ISSUE THREAD

**Issue by Tdue21** [deadlydog/Invoke-MsBuild#9]
Currently the log file will always be defined as: 
/fileLoggerParameters:LogFile=""$buildLogFilePath"" 

Whereas I would like to be able to set the verbosity:
/flp1:"logfile=msbuild.log;Verbosity=Normal;Append;"

**Comment by Tdue21** [comment]
#10

**Comment by Jerome2606** [comment]
+1

**Comment by deadlydog** [comment]
Pull request has been merged and new NuGet package published. Thanks! P.S. Sorry it took so long for me to notice this.
